name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.12, 3.13]
    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies for PySide6
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libegl1-mesa \
            libgl1-mesa-glx \
            libgl1-mesa-dri \
            libx11-6 \
            libxcb1 \
            libxext6 \
            libxrender1 \
            libxi6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          PYTHONPATH=. pytest --maxfail=1 --disable-warnings -q
